"use client"

import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"
import { Flame, Medal, Star, Trophy, Zap } from "lucide-react"
import { api } from "@/lib/api-client"
import type { ProgressSummary, BadgeInfo, Leaderboard } from "@/lib/api-client"
import { ProgressStat } from "@/components/user/ProgressStat"
import { StreakCalendar } from "@/components/user/StreakCalendar"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent } from "@/components/ui/card"
import { digits, fmt } from "@/lib/utils"

export default function ProgressPage() {
  const router = useRouter(); const [progress, setProgress] = useState<ProgressSummary | null>(null); const [badges, setBadges] = useState<BadgeInfo[]>([]); const [leaderboard, setLeaderboard] = useState<Leaderboard | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  useEffect(() => { const load = async () => { try { const [p, b, l] = await Promise.all([api.getProgress(), api.getBadges(), api.getLeaderboard()]); setProgress(p); setBadges(b.badges); setLeaderboard(l) } catch (err: any) { if (err?.status === 401) { router.push("/app/login"); return }; setError("بارگذاری پیشرفت ناموفق بود") } finally { setLoading(false) } }; load() }, [router])
  if (loading) return <div className="flex min-h-[60vh] items-center justify-center"><div className="h-9 w-9 animate-spin rounded-full border-4 border-primary/20 border-t-primary" /></div>
  return <div className="space-y-6">
    <section><p className="text-sm text-muted-foreground">آمار مسیر شما</p><h1 className="mt-1 text-2xl font-extrabold">پروفایل شایستگی‌ها و مهارت‌ها</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">سنجش واقعی بر مبنای تصمیماتی که در سناریوها انتخاب کرده‌اید.</p></section>
    {error && <div role="alert" className="rounded-xl border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>}
    {progress && <>
      <div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><ProgressStat label={"امتیاز"} value={progress.totalXp} icon={Zap} /><ProgressStat label={"تداوم فعالیت"} value={progress.streak.currentStreak} icon={Flame} tone="gold" /><ProgressStat label={"مرحله"} value={progress.playerLevel} icon={Trophy} tone="blue" /><ProgressStat label={"ستاره‌ها"} value={progress.totalStars} icon={Star} tone="rose" /></div>
      <Card className="border-amber-200 bg-amber-50"><CardContent className="flex items-center gap-3 py-4"><Flame className="shrink-0 text-orange-600" size={24} fill="currentColor" aria-hidden /><div><p className="font-bold text-amber-950">{fmt("تداوم فعالیت: {n} روز", { n: digits(progress.streak.currentStreak) })}</p><p className="text-xs text-amber-900/75">{fmt("بیشترین تداوم فعالیت: {n} روز", { n: digits(progress.streak.longestStreak) })}</p></div></CardContent></Card>
      <Card><CardContent className="space-y-4 py-5"><h2 className="font-extrabold">فعالیت هفت روز گذشته</h2><StreakCalendar activityDays={progress.activityDays} /></CardContent></Card>
      <Card><CardContent className="space-y-3 py-5"><div className="flex items-center justify-between gap-3"><h2 className="font-extrabold">تا سطح بعدی</h2><span className="text-sm font-bold text-primary">سطح {digits(progress.playerLevel + 1)}</span></div><div className="h-3 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${Math.min(100, Math.max(0, (progress.totalXp - progress.xpLevelStart) / (progress.xpNextLevel - progress.xpLevelStart) * 100))}%` }} /></div><p className="text-xs text-muted-foreground">{digits(progress.totalXp)} از {digits(progress.xpNextLevel)} امتیاز · {digits(Math.max(0, progress.xpNextLevel - progress.totalXp))} امتیاز مانده</p></CardContent></Card>
      <section className="space-y-3"><h2 className="text-lg font-extrabold">صنایع</h2>{progress.industries.map(industry => { const percent = industry.levelsTotal ? Math.round(industry.levelsPassed / industry.levelsTotal * 100) : 0; return <Card key={industry.id}><CardContent className="space-y-3 py-4"><div className="flex items-center justify-between gap-3"><div><p className="font-bold">{industry.name}</p><p className="mt-1 text-xs text-muted-foreground">{fmt("{passed} از {total} مرحله پاس شده", { passed: digits(industry.levelsPassed), total: digits(industry.levelsTotal) })}</p></div><span className="text-sm font-bold text-amber-600">{digits(industry.stars)}★</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${percent}%` }} /></div></CardContent></Card> })}</section>
      <section className="space-y-3"><h2 className="text-lg font-extrabold">جدول امتیاز هفتگی</h2><Card><CardContent className="space-y-3 py-4">{leaderboard?.leaderboard.length ? leaderboard.leaderboard.map(row => <div key={row.userId} className="flex items-center justify-between rounded-xl bg-muted/50 px-3 py-3 text-sm"><span className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-card font-bold">{digits(row.rank)}</span><span>{row.player}</span></span><span className="font-semibold">{fmt("{xp} امتیاز", { xp: digits(row.weeklyXp) })}</span></div>) : <p className="text-sm text-muted-foreground">هنوز در گروه شما امتیازی کسب نشده است.</p>}{leaderboard?.userRank && <p className="border-t pt-3 text-sm font-medium text-primary">{fmt("شما: #{rank} با {xp} امتیاز در این هفته", { rank: digits(leaderboard.userRank.rank), xp: digits(leaderboard.userRank.weeklyXp) })}</p>}</CardContent></Card></section>
      <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-lg font-extrabold">مدال‌ها و دستاوردها</h2><Link href="/app/badges" className="text-sm font-bold text-primary">دیدن همه</Link></div><div className="grid gap-3 sm:grid-cols-2">{badges.filter(badge => badge.earned).slice(-2).map(badge => <Card key={badge.id}><CardContent className="flex gap-3 py-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-amber-50 text-xl">{badge.iconRef || "★"}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-bold">{badge.name}</p><Badge variant="success">کسب شد</Badge></div><p className="mt-1 text-sm leading-6 text-muted-foreground">{badge.description}</p></div></CardContent></Card>)}</div>{badges.every(badge => !badge.earned) && <p className="text-sm text-muted-foreground">هنوز مدالی باز نکرده‌اید. با گذراندن مراحل بیشتر مدال‌ها را کسب کنید!</p>}</section>
    </>}
  </div>
}
