"use client"

import { useEffect, useState } from "react"
import Link from "next/link"
import { Check, LockKeyhole, Target } from "lucide-react"
import { api, type SkillTree } from "@/lib/api-client"
import { digits } from "@/lib/utils"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export default function SkillsPage() {
  const [tree, setTree] = useState<SkillTree | null>(null)
  const [error, setError] = useState<string | null>(null)
  useEffect(() => { api.getSkillTree().then(setTree).catch(() => setError('درخت مهارت بارگذاری نشد.')) }, [])
  if (!tree && !error) return <div className="py-20 text-center text-sm text-muted-foreground">در حال بارگذاری مهارت‌ها…</div>
  return <div className="space-y-5"><section><p className="text-sm font-bold text-primary">مهارت‌های نقش شما</p><h1 className="mt-1 text-2xl font-extrabold">درخت مهارت</h1><p className="mt-2 text-sm leading-7 text-muted-foreground">تصمیم‌هایتان امتیاز هر مهارت را می‌سازند. وقتی در یک مهارت به {digits(tree?.threshold ?? 60)}٪ برسید، گرهٔ بعدی باز می‌شود.</p></section>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<ol className="space-y-3">{tree?.skills.map((skill, index) => {
    const nextPractice = skill.challenges.find(level => level.playable && !level.passed) ?? skill.challenges.find(level => level.playable)
    return <li key={skill.id} className="relative"><Card className={skill.status === 'locked' ? 'bg-muted/30' : skill.status === 'current' ? 'border-primary/40' : ''}><CardContent className="space-y-3 py-5"><div className="flex items-start gap-3"><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-full font-extrabold ${skill.status === 'mastered' ? 'bg-primary text-primary-foreground' : skill.status === 'locked' ? 'bg-muted text-muted-foreground' : 'border-2 border-primary text-primary'}`}>{skill.status === 'mastered' ? <Check size={20} /> : skill.status === 'locked' ? <LockKeyhole size={18} /> : digits(index + 1)}</span><div className="min-w-0 flex-1"><h2 className="font-extrabold">{skill.name}</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">{skill.blurb}</p></div><span className="text-sm font-extrabold text-primary">{skill.count ? `${digits(Math.round(skill.rate * 100))}٪` : '—'}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${Math.round(skill.rate * 100)}%` }} /></div><p className="text-xs text-muted-foreground">{skill.count === 0 ? 'هنوز تصمیمی برای سنجش این مهارت ثبت نشده است.' : `${digits(skill.completedChallenges)} از ${digits(skill.challenges.length)} چالش مرتبط کامل شده · ${digits(skill.count)} تصمیم سنجیده‌شده`}</p>{skill.status === 'locked' ? <p className="rounded-lg bg-muted px-3 py-2 text-xs">برای بازشدن این مهارت، در «{tree.skills[index - 1]?.name}» به {digits(tree.threshold)}٪ برسید.</p> : <>{skill.status === 'current' && <p className="rounded-lg bg-primary/5 px-3 py-2 text-xs leading-6 text-primary">{skill.count === 0 ? 'با یک تمرین مرتبط، سنجش این مهارت را شروع کنید.' : `برای رسیدن به ${digits(tree.threshold)}٪ و بازشدن مهارت بعدی، این مهارت را تمرین کنید.`}</p>}{skill.status === 'current' && nextPractice && <Button asChild className="touch-target h-auto w-full whitespace-normal px-4 py-3 text-center leading-6"><Link href={`/levels/${nextPractice.id}`}>تمرین «{skill.name}» · مرحلهٔ {digits(nextPractice.number)}</Link></Button>}{skill.challenges.length > 0 && <details className="rounded-xl border px-3 py-2"><summary className="cursor-pointer text-sm font-bold text-primary">همهٔ چالش‌های مرتبط</summary><ul className="mt-3 space-y-2">{skill.challenges.map(level => <li key={level.id}>{level.playable ? <Link href={`/levels/${level.id}`} className="flex items-center gap-2 text-sm text-primary hover:underline"><Target size={15} />مرحلهٔ {digits(level.number)}: {level.title}{level.passed ? ' ✓' : ''}</Link> : <span className="flex items-center gap-2 text-sm text-muted-foreground"><LockKeyhole size={14} />مرحلهٔ {digits(level.number)}: {level.title} · پس از مرحلهٔ قبلی</span>}</li>)}</ul></details>}</>}</CardContent></Card></li>
  })}</ol></div>
}
